services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - /home/huatansang/Documents/MLOps-Lab/Lab1/artifacts/ac4b5fd93b7d41b2a2f27dd31cde4a75/artifacts/checkpoints/best_model:/model

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/predict
    command: streamlit run frontend.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - backend
